"""list of str for Recipe directions

Revision ID: 3cbb76ed5473
Revises: ea523ef9c3c5
Create Date: 2023-08-22 11:48:00.256041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3cbb76ed5473'
down_revision = 'ea523ef9c3c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
